
[package]
name = "solders-primitives"
version = "0.23.0"
edition = "2021"
include = ["/src"]
license = "MIT"
repository = "https://github.com/kevinheavey/solders"
description = "Solders primitives crate."

[dependencies]
bv = "0.11.1"
pyo3 = { version = "0.23", default-features = false , features = ["macros"] }
solders-hash = { path = "../solders-hash" }
solders-traits-core = { path = "../solders-traits-core" }
solders-macros = { path = "../solders-macros" }
solana-program = "2.1.0"
serde = "^1.0.188"
derive_more = "0.99.17"
bincode = "1.3.3"
