[tool.poetry]
name = "flakeranker"
version = "0.0.3"
description = "Understanding and Prioritizing Flaky Job Failure Categories"
authors = ["Henri AÃ¯dasso <ahenrij@gmail.com>"]
readme = "example/README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2.2"
clean-text = {extras = ["gpl"], version = "^0.6.0"}
scikit-learn = "^1.5.0"
click = "^8.1.8"
pydantic = "^2.10.5"
pydantic-settings = "^2.7.1"
tqdm = "^4.67.1"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"
kaleido = "0.2.1"
nbformat = "^5.10.4"
matplotlib = "^3.8.4"
plotly = "^5.21.0"

[tool.poetry.scripts]
flakeranker = "src.flakeranker.cli.main:cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
name = "flakeranker"
authors = [{name = "Henri", email = "ahenrij@gmail.com"}]
dynamic = ["version", "description"]
