[project]
name = "langmem"
version = "0.0.5rc5"
description = "Prebuilt utilities for memory management and retrieval."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=0.3.15",
    "langchain-openai>=0.3.1",
    "trustcall>=0.0.28",
    "langgraph>=0.2.66",
]

[dependency-groups]
dev = ["langchain-anthropic>=0.3.3", "langchain-openai>=0.3.1"]
