[project]
name = "soda-conan-server"
version = "2025.1.26.0"
description = "soda's conan server"
readme = "README_soda.md"
requires-python = ">=3.10"
dependencies = [
    "bottle>=0.13.2",
    "fasteners>=0.19",
    "jinja2>=3.1.5",
    "patch-ng>=1.18.1",
    "pluginbase>=1.0.1",
    "pyjwt>=2.10.1",
    "python-dateutil>=2.9.0.post0",
    "pyyaml>=6.0.2",
    "urllib3>=2.3.0",
]

[project.urls]
Repository = "https://github.com/soda92/conan/tree/my-server"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.hatch.build.targets.wheel]
packages = ["conan", "conans"]

[tool.hatch.build.targets.sdist]
packages = ["conan", "conans"]

[dependency-groups]
dev = ["build>=1.2.2.post1", "twine>=6.1.0"]

[project.scripts]
conan_server = "conans.conan_server:run"
conan = "conans.conan:run"
