[project]
name = "tinyconfig"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[[project.authors]]
name = "Hamlet"
email = "hamlets849@gmail.com"

[project.license]
text = "MIT"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
