[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "skribble-sdk"
version = "0.14"
description = "A Python SDK for the Skribble API"
readme = "README.md"
authors = [{ name = "Eric Campos", email = "ec@webix.ch" }]
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
keywords = ["skribble", "api", "sdk"]
dependencies = [
    "requests",
    "pydantic",
]
requires-python = ">=3.7"

[project.optional-dependencies]
test = ["unittest", "coverage"]

[project.urls]
Homepage = "https://github.com/LeEricCH/skribble-sdk"
Documentation = "https://skribblesdk.mintlify.app/"
Repository = "https://github.com/LeEricCH/skribble-sdk.git"

[tool.setuptools.packages.find]
include = ["skribble*"]

[tool.setuptools.package-data]
skribble = ["py.typed"]