[project]
name = "retan"
version = "0.1.1"
description = "A cli helper tool that helps with day to day cli commands and automates software development"
authors = [
    {name = "tanveer", email = "tanvoid0@gmail.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.8,<3.13"

dependencies = [
    "click",
    "colorama",
    "textual",
    "ollama"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
pilot = "retan:cli"

[tool.poetry]
exclude = ['assets']