[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
[project]
name = "reposlayer"
version = "0.1.1"
requires-python = ">=3.6"
authors = [
    {name = "Richard Qu", email = "rq2014@nyu.edu"},
]
maintainers = [
    {name = "Richard Qu", email = "rq2014@nyu.edu"},
]
description = "Python repository manager"
readme = {file = "README.md", content-type = "text/markdown"}
keywords = ["python", "repository", "manager"]
classifiers =[
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pathlib",
]

[project.scripts]
reposlayer = "reposlayer.cli:main"