[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "cw-rpa-unified-logger"
version = "0.1.0rc3"
description = "Unified logging system with Discord and Asio integrations"
authors = [ "VinnyVanGogh <133192356+VinnyVanGogh@users.noreply.github.com>",]
license = "MIT"
readme = "README.md"
[[tool.poetry.packages]]
include = "cw_rpa_unified_logger"

[tool.poetry.dependencies]
python = "^3.11"
colorlog = "^6.9.0"
cw-rpa = "^0.1.0b10"
aiohttp = "^3.11.11"
