[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "healthcare-edi-converter"  # Must be unique on PyPI
version = "0.0.3"
description = "A Python library to convert healthcare edi data (837p Claims etc)"
readme = "README.md"
license = {file = "LICENSE"}
authors = [{name = "CloudFocus, LLC", email = "chad@CloudFocus.tech"}]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pandas>=1.3.0",
    "fastparquet>=2024.11.0",
    "numpy>=2.2.2",
    "pyarrow>=19.0.0",
    "pyx12>=2.3.3",
    "pyparsing>=3.0.0",
    
]
requires-python = ">=3.7"

[project.urls]
Homepage = "https://www.cloudfocus.tech"
Repo = "https://github.com/CloudFocused/healthcare-edi-converter"