
[package]
name = "solders-traits"
version = "0.23.0"
edition = "2021"
include = ["/src"]
description = "A collection of traits and helpers for Solders."
license = "MIT"
repository = "https://github.com/kevinheavey/solders"

[dependencies]
pyo3 = { version = "0.23", default-features = false }
solana-sdk = { version = "2.1.0", features = ["openssl-vendored"] }
bincode = "1.3.3"
litesvm = { version = "0.5.0", optional = true }
serde_json = "^1.0.106"
serde_cbor = "^0.11.2"
solders-traits-core = { path = "../solders-traits-core" }
solana-banks-client = { version = "2.1.0", optional = true }

[features]
banks-client = ["dep:solana-banks-client"]
litesvm = ["dep:litesvm"]
