[project]
name = "gdmo"
version = "0.0.91"
description = "GDMO native classes for standardized interaction with data objects within Azure Databricks. Contains TimeSeriesForecasting, APIRequest, Landing, Delta, GoldConsolidation, and DBx functions."
readme = "README.md"
requires-python = ">=3.8"
authors = [{name = "Stephan Kuiper"},{name = "Taylor Fialkowski"}]
license = {text = "Apache-2.0"}
classifiers = [
    "License :: OSI Approved :: Apache Software License"
]
dependencies = [
  "pandas",
  "numpy",
  "matplotlib",
  "prophet",
  "scipy",
  "pyspark",
  "delta-spark",
  "requests",
  "Office365-REST-Python-Client",
  "adal"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/StephanKuiper-Insight/gdmo"
Changelog = "https://github.com/StephanKuiper-Insight/gdmo/releases"
Issues = "https://github.com/StephanKuiper-Insight/gdmo/issues"
CI = "https://github.com/StephanKuiper-Insight/gdmo/actions"