[tool.poetry]
name = "sqthon"
version = "0.1.3"
description = "A tool to connect, visualize and execute raw or LLM-generated SQL queries across multiple databases."
authors = ["HIMRAJ <himraj.fordev@gmail.com>"]
readme = "README.md"
license = "MIT"


[tool.poetry.dependencies]
python = "^3.12"
sqlalchemy = "^2.0"
pandas = "^2.2.2"
seaborn = "^0.13.2"
matplotlib = "^3.9.2"
python-dotenv = "^1.0.1"
cryptography = "^43.0.0"
psycopg2 = "^2.9.9"
ollama = "^0.3.3"
requests = "^2.32.3"
pywin32 = "^306"
pymysql = "^1.1.1"
openai = "^1.57.3"
tenacity = "^9.0.0"
tiktoken = "^0.8.0"
rich = "^13.9.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"



