[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "empire-chain"
version = "0.3.14"
description = "An orchestration framework for all your AI needs"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai",
    "anthropic",
    "groq",
    "python-dotenv",
    "qdrant-client"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["empire_chain*"]