[project]
name = "kalle"
version = "0.0.3"
description = "A smart CLI friend"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "aiohttp>=3.11.11",
    "anthropic>=0.44.0",
    "atproto>=0.0.57",
    "bs4>=0.0.2",
    "coverage>=7.6.10",
    "docling>=2.15.1",
    "espeakng>=1.0.3",
    "fastembed>=0.5.1",
    "google>=3.0.0",
    "google-api-python-client>=2.159.0",
    "google-auth>=2.37.0",
    "google-auth-oauthlib>=1.2.1",
    "groq>=0.15.0",
    "httpx==0.27.2",
    "llama-cpp-python>=0.3.6",
    "markdownify>=0.14.1",
    "mistral-common>=1.5.1",
    "openai>=1.60.0",
    "pip-licenses>=5.0.0",
    "platformdirs>=4.3.6",
    "pydantic>=2.10.5",
    "pypdf>=5.1.0",
    "python-magic>=0.4.27",
    "pytz>=2024.2",
    "pyyaml>=6.0.2",
    "rich-argparse>=1.6.0",
    "sentencepiece>=0.2.0",
    "textual>=1.0.0",
    "tiktoken>=0.7.0",
    "transformers>=4.48.1",
    "vertexai>=1.71.1",
]

[dependency-groups]
dev = [
    "build>=1.2.2.post1",
    "coverage>=7.6.10",
    "lorem-text>=2.1",
    "pyink>=24.10.1",
    "pyinstrument>=5.0.0",
    "pyright>=1.1.392.post0",
    "ruff>=0.9.3",
    "textual-dev>=1.7.0",
    "twine>=6.1.0",
]
[project.urls]
Homepage = "https://codeberg.org/fe2/kalle"
Repository = "https://codeberg.org/fe2/kalle"
Issues = "https://codeberg.org/fe2/kalle/issues"
Documentation = "https://codeberg.org/fe2/kalle/src/branch/main/docs"

[project.scripts]
kalle = "kalle.cli.kalle:cli"
conversationmanager = "kalle.cli.conversationmanager:cli"
patterneditor = "kalle.cli.patterneditor:cli"
kalle_profiles = "kalle.cli.profiles:cli"
kalle_tools = "kalle.cli.tools:cli"

[tool.setuptools]
script-files = ["bin/kalle_conversations", "bin/kalle_patterns"]

[tool.setuptools.packages]
find = {}

[tool.pyright]
include = ["kalle"]
