
[package]
name = "solders-rpc-send-transaction-config"
version = "0.23.0"
edition = "2021"
include = ["/src"]
license = "MIT"
repository = "https://github.com/kevinheavey/solders"
description = "Solders RPC send transaction config crate."

[dependencies]
pyo3 = { version = "0.23", default-features = false , features = ["macros"] }
serde = "^1.0.188"
solders-macros = { path = "../solders-macros" }
solana-sdk = { version = "2.1.0", features = ["openssl-vendored"] }
solana-rpc-client-api = "2.1.0"
solders-rpc-config-macros = { path = "../solders-rpc-config-macros" }
solders-commitment-config = { path = "../solders-commitment-config" }
solders-traits-core = { path = "../solders-traits-core" }
solana-transaction-status-client-types = "2.1.0"
solders-transaction-status-enums = { path = "../solders-transaction-status-enums" }
