
[package]
name = "solders-transaction-status"
version = "0.23.0"
edition = "2021"
include = ["/src"]
license = "MIT"
repository = "https://github.com/kevinheavey/solders"
description = "Solders transaction status crate."

[dependencies]
pyo3 = { version = "0.23", default-features = false , features = ["macros"] }
solana-sdk = { version = "2.1.0", features = ["openssl-vendored"] }
serde = "^1.0.188"
serde_json = "^1.0.106"
derive_more = "0.99.17"
pythonize = "0.23"
solders-pubkey = { path = "../solders-pubkey" }
solders-signature = { path = "../solders-signature" }
solders-macros = { path = "../solders-macros" }
base64 = "0.13.0"
bs58 = "0.4.0"
solders-traits-core = { path = "../solders-traits-core" }
solana-account-decoder-client-types = { version = "2.1.0", features = ["zstd"] }
solders-account-decoder = { path = "../solders-account-decoder" }
solders-hash = { path = "../solders-hash" }
solders-message = { path = "../solders-message" }
solders-transaction = { path = "../solders-transaction" }
solana-transaction-status-client-types = "2.1.0"
solders-transaction-error = { path = "../solders-transaction-error" }
solders-transaction-confirmation-status = { path = "../solders-transaction-confirmation-status" }
solders-transaction-return-data = { path = "../solders-transaction-return-data" }
solders-transaction-status-enums = { path = "../solders-transaction-status-enums" }
solders-transaction-status-struct = { path = "../solders-transaction-status-struct" }
bincode = "1.3.3"
