[project]
name = "blemli-mail"
version = "0.0.2"
authors = [
  { name="Problemli GmbH", email="info@problem.li" },
]
description = "quickly send a mail to problemli (or to someone else)"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
# Define project dependencies here
dependencies = [
  "python-dotenv>=1.0.1",
  "icecream>=2.1.3"
]
[project.urls]
Homepage = "https://github.com/blemli/blemli_mail"
Issues = "https://github.com/blemli/blemli_mail/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
